// Code generated by mockery v2.35.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// INotifier is an autogenerated mock type for the INotifier type
type INotifier struct {
	mock.Mock
}

// NotifyOfUserCreated provides a mock function with given fields: id
func (_m *INotifier) NotifyOfUserCreated(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewINotifier creates a new instance of INotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *INotifier {
	mock := &INotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
